### ISSUE TITLE
Neues Feature: (Individuelles) Styling von öffentlichen Events

### ISSUE THREAD

**Issue by MarkusTiede** [hitobito/hitobito_digisus_lab#5]
Logo, Look & Feel, Einbindung in in externe Webseiten

**Comment by kronn** [comment]
Durch die API ist es ja bereits möglich, die Daten eines Events auch an anderen Stellen anzuzeigen. Siehe: https://github.com/hitobito/hitobito/blob/master/doc/development/README.md#schnittstellen

Fehlt hier noch etwas bestimmtes?

**Comment by MarkusTiede** [comment]
Vielen Dank für die Rückmeldung: gibt es neben dieser "low-level" Integration auf API-Ebene bereits bestimmte Plug-ins z.B für gängige CMS Systeme?

**Comment by kronn** [comment]
Mir sind zumindest keine Plugins bekannt. Wenn Sie so ein Plugin kennen oder bauen, richte ich gerne eine Seite mit bekannten Integrationen ein. 

Aktuell ist mir nur eine Integration bekannt, die aber sehr individuell ist. Da die Schnittstelle jedoch auch dem JSON-API-Standard entspricht, könnte vielleicht auch ein generisches Plugin für Wordpress und Co exisiteren, dass zumindest eine einfache Liste von Anlässen zeigen kann.

**Comment by kronn** [comment]
Ich schliesse das Issue hier erstmal, da ich hier direkt nichts machen kann. Ich informiere aber mal das Team, dass dieser Wunsch besteht. Allenfalls könnte das auch noch für das Community-Meeting interessant sein.
